* Forthnet SMS
** About
This is a simple script using Python's *Mechanize* library.
It is written in order to avoid the use of Forthnet's WebSMS Service website, when sending text-messages.
Its use is simple. Just follow the instructions and write the phone number and the text-message you would like to send.

** Dependencies
   - Mechanize Library (http://pypi.python.org/pypi/mechanize)
   - Python

** Installation
   - To install *mechanize*: 
     - using pip: /pip install mechanize/ 
     - using easy_install: /easy_install mechanize/
     - you can also download *mechanize* from (http://pypi.python.org/pypi/mechanize) and run /python setup.py install/ (or read the INSTALL.txt)
   - To configure *ForthnetSms.py* open the script and change the *login_email* and *password* variables properly.


** For android users:

   - Install the Python interpreter (SL4A > Menu > View > Interpreters and then Add>Python)
   - In order to use mechanize library with SL4A Python interpreter in Αndroid, just download the latest .tar from http://pypi.python.org/pypi/mechanize
     and extract *only* the source folder inside the folder with the rest of your scripts.
     Then you can import the library as usually (/import mechanize/).



